apiVersion: v1
kind: Service
metadata:
  name: pastang-minimalistic
  labels:
    app: pastang-minimalistic

spec:
  clusterIP: None
  selector:
    app: pastang-minimalistic

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pastang-minimalistic
  labels:
    app: pastang-minimalistic

spec:
  replicas: 1
  selector:
    matchLabels:
      app: pastang-minimalistic
  
  template:
    metadata:
      labels:
        app: pastang-minimalistic
    
    spec:
      containers:
      - name: pastang-minimalistic
  
        image: skaf-pasta-ror7
