# docker-compose.yaml
# from: https://revs.runtime-revolution.com/setting-up-a-simple-rails-development-environment-with-docker-for-fun-and-profit-71b8aa0d33c1
version: '2'
services:
  database:
    image: postgres
    volumes:
      - ./data/pgdata:/pgdata
    env_file:
      - '.env'
  web:
    links:
      - database
    build: .
    volumes:
      - .:/opt/pasta
    ports:
      - '3000:3000'
    command: [bundle, exec, puma]
    env_file:
      - '.env'
