# https://stackoverflow.com/questions/51466887/rails-how-to-fix-missing-secret-key-base-for-production-environment
production:
  secret_key_base: <%= ENV["RICCARDO_SECRET_KEY_BASE"] %>
  my_gcp_secret: abcde
  some_password: abcdex

development:
  secret_key_base: static_secret_key
  my_gcp_secret: abcde

test:
  secret_key_base: static_test_secret_key


#not_indented: key for all env in once
secret_key_base: global_key_for_all_env
